version: "3.3"
services:
  frontend:
    hostname: react
    build: 
      context: .
      dockerfile: ./sdg_frontend/Dockerfile
    ports:
      - "3000:3000"
  
  backend:
    hostname: node
    build:
      context: .
      dockerfile: ./sdg_backend/Dockerfile
    ports:
      - "8080:8080"