version: "3.3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432"
  frontend:
    hostname: react
    build: 
      context: .
      dockerfile: ./sdg_frontend/Dockerfile
    depends_on: 
      - db
    ports:
      - "3000:3000"
  
  backend:
    hostname: node
    build:
      context: .
      dockerfile: ./sdg_backend/Dockerfile
    depends_on: 
      - db
    ports:
      - "8080:8080"